package cn.edu.jit.mapper;

import cn.edu.jit.po.LogicSubmission;

public interface LogicSubmissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logic_submission
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logic_submission
     *
     * @mbggenerated
     */
    int insert(LogicSubmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logic_submission
     *
     * @mbggenerated
     */
    int insertSelective(LogicSubmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logic_submission
     *
     * @mbggenerated
     */
    LogicSubmission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logic_submission
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogicSubmission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logic_submission
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogicSubmission record);
}