package cn.edu.jit.mapper;

import cn.edu.jit.po.StudentMaxScoreView;

import java.util.List;
import java.util.Map;

public interface StudentMaxScoreViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_max_score_view
     *
     * @mbggenerated
     */
    int insert(StudentMaxScoreView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_max_score_view
     *
     * @mbggenerated
     */
    int insertSelective(StudentMaxScoreView record);

    List select(Map map);

    int selectCount(Map map);

    StudentMaxScoreView selectByStudentId(Map map);
}