package cn.edu.jit.po;

public class LogicSubmission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic_submission.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic_submission.submission_id
     *
     * @mbggenerated
     */
    private Integer submissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic_submission.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic_submission.x
     *
     * @mbggenerated
     */
    private Integer x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logic_submission.y
     *
     * @mbggenerated
     */
    private Integer y;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic_submission.id
     *
     * @return the value of logic_submission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic_submission.id
     *
     * @param id the value for logic_submission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic_submission.submission_id
     *
     * @return the value of logic_submission.submission_id
     *
     * @mbggenerated
     */
    public Integer getSubmissionId() {
        return submissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic_submission.submission_id
     *
     * @param submissionId the value for logic_submission.submission_id
     *
     * @mbggenerated
     */
    public void setSubmissionId(Integer submissionId) {
        this.submissionId = submissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic_submission.type
     *
     * @return the value of logic_submission.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic_submission.type
     *
     * @param type the value for logic_submission.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic_submission.x
     *
     * @return the value of logic_submission.x
     *
     * @mbggenerated
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic_submission.x
     *
     * @param x the value for logic_submission.x
     *
     * @mbggenerated
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logic_submission.y
     *
     * @return the value of logic_submission.y
     *
     * @mbggenerated
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logic_submission.y
     *
     * @param y the value for logic_submission.y
     *
     * @mbggenerated
     */
    public void setY(Integer y) {
        this.y = y;
    }

    public LogicSubmission(Integer x, Integer y) {
        this.x = x;
        this.y = y;
    }

    public LogicSubmission(Integer x, Integer y, int type) {
        this.x = x;
        this.type = type;
        this.y = y;
    }
}