package cn.edu.jit.po;

public class RqtsSubmission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rqts_submission.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rqts_submission.submission_id
     *
     * @mbggenerated
     */
    private Integer submissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rqts_submission.year
     *
     * @mbggenerated
     */
    private Integer year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rqts_submission.month
     *
     * @mbggenerated
     */
    private Short month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rqts_submission.day
     *
     * @mbggenerated
     */
    private Short day;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rqts_submission.id
     *
     * @return the value of rqts_submission.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rqts_submission.id
     *
     * @param id the value for rqts_submission.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rqts_submission.submission_id
     *
     * @return the value of rqts_submission.submission_id
     *
     * @mbggenerated
     */
    public Integer getSubmissionId() {
        return submissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rqts_submission.submission_id
     *
     * @param submissionId the value for rqts_submission.submission_id
     *
     * @mbggenerated
     */
    public void setSubmissionId(Integer submissionId) {
        this.submissionId = submissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rqts_submission.year
     *
     * @return the value of rqts_submission.year
     *
     * @mbggenerated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rqts_submission.year
     *
     * @param year the value for rqts_submission.year
     *
     * @mbggenerated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rqts_submission.month
     *
     * @return the value of rqts_submission.month
     *
     * @mbggenerated
     */
    public Short getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rqts_submission.month
     *
     * @param month the value for rqts_submission.month
     *
     * @mbggenerated
     */
    public void setMonth(Short month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rqts_submission.day
     *
     * @return the value of rqts_submission.day
     *
     * @mbggenerated
     */
    public Short getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rqts_submission.day
     *
     * @param day the value for rqts_submission.day
     *
     * @mbggenerated
     */
    public void setDay(Short day) {
        this.day = day;
    }

    public String toString(){
        return this.getYear()+"-"+this.getMonth()+"-"+getDay();
    }
}