package cn.edu.jit.po;

public class StudentMaxScoreView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_max_score_view.studentId
     *
     * @mbggenerated
     */
    private String studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_max_score_view.studentName
     *
     * @mbggenerated
     */
    private String studentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_max_score_view.classId
     *
     * @mbggenerated
     */
    private Integer classid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_max_score_view.className
     *
     * @mbggenerated
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_max_score_view.session
     *
     * @mbggenerated
     */
    private Integer session;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_max_score_view.major
     *
     * @mbggenerated
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_max_score_view.questionId
     *
     * @mbggenerated
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student_max_score_view.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_max_score_view.studentId
     *
     * @return the value of student_max_score_view.studentId
     *
     * @mbggenerated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_max_score_view.studentId
     *
     * @param studentid the value for student_max_score_view.studentId
     *
     * @mbggenerated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_max_score_view.studentName
     *
     * @return the value of student_max_score_view.studentName
     *
     * @mbggenerated
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_max_score_view.studentName
     *
     * @param studentname the value for student_max_score_view.studentName
     *
     * @mbggenerated
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname == null ? null : studentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_max_score_view.classId
     *
     * @return the value of student_max_score_view.classId
     *
     * @mbggenerated
     */
    public Integer getClassid() {
        return classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_max_score_view.classId
     *
     * @param classid the value for student_max_score_view.classId
     *
     * @mbggenerated
     */
    public void setClassid(Integer classid) {
        this.classid = classid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_max_score_view.className
     *
     * @return the value of student_max_score_view.className
     *
     * @mbggenerated
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_max_score_view.className
     *
     * @param classname the value for student_max_score_view.className
     *
     * @mbggenerated
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_max_score_view.session
     *
     * @return the value of student_max_score_view.session
     *
     * @mbggenerated
     */
    public Integer getSession() {
        return session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_max_score_view.session
     *
     * @param session the value for student_max_score_view.session
     *
     * @mbggenerated
     */
    public void setSession(Integer session) {
        this.session = session;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_max_score_view.major
     *
     * @return the value of student_max_score_view.major
     *
     * @mbggenerated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_max_score_view.major
     *
     * @param major the value for student_max_score_view.major
     *
     * @mbggenerated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_max_score_view.questionId
     *
     * @return the value of student_max_score_view.questionId
     *
     * @mbggenerated
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_max_score_view.questionId
     *
     * @param questionid the value for student_max_score_view.questionId
     *
     * @mbggenerated
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student_max_score_view.score
     *
     * @return the value of student_max_score_view.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student_max_score_view.score
     *
     * @param score the value for student_max_score_view.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}