package cn.edu.jit.po;

import java.text.SimpleDateFormat;
import java.util.Date;

public class SubmissionQuestionView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission_question_view.submissionId
     *
     * @mbggenerated
     */
    private Integer submissionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission_question_view.studentId
     *
     * @mbggenerated
     */
    private String studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission_question_view.questionId
     *
     * @mbggenerated
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission_question_view.questionTitle
     *
     * @mbggenerated
     */
    private String questiontitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission_question_view.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submission_question_view.submitTime
     *
     * @mbggenerated
     */
    private Date submittime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission_question_view.submissionId
     *
     * @return the value of submission_question_view.submissionId
     *
     * @mbggenerated
     */
    public Integer getSubmissionid() {
        return submissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission_question_view.submissionId
     *
     * @param submissionid the value for submission_question_view.submissionId
     *
     * @mbggenerated
     */
    public void setSubmissionid(Integer submissionid) {
        this.submissionid = submissionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission_question_view.studentId
     *
     * @return the value of submission_question_view.studentId
     *
     * @mbggenerated
     */
    public String getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission_question_view.studentId
     *
     * @param studentid the value for submission_question_view.studentId
     *
     * @mbggenerated
     */
    public void setStudentid(String studentid) {
        this.studentid = studentid == null ? null : studentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission_question_view.questionId
     *
     * @return the value of submission_question_view.questionId
     *
     * @mbggenerated
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission_question_view.questionId
     *
     * @param questionid the value for submission_question_view.questionId
     *
     * @mbggenerated
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission_question_view.questionTitle
     *
     * @return the value of submission_question_view.questionTitle
     *
     * @mbggenerated
     */
    public String getQuestiontitle() {
        return questiontitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission_question_view.questionTitle
     *
     * @param questiontitle the value for submission_question_view.questionTitle
     *
     * @mbggenerated
     */
    public void setQuestiontitle(String questiontitle) {
        this.questiontitle = questiontitle == null ? null : questiontitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission_question_view.score
     *
     * @return the value of submission_question_view.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission_question_view.score
     *
     * @param score the value for submission_question_view.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submission_question_view.submitTime
     *
     * @return the value of submission_question_view.submitTime
     *
     * @mbggenerated
     */
    public String getSubmittime() {
        SimpleDateFormat dateFormater = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return dateFormater.format(submittime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submission_question_view.submitTime
     *
     * @param submittime the value for submission_question_view.submitTime
     *
     * @mbggenerated
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }
}